export const employeeCreateText = {
  vi: {
    title: 'Thêm nhân viên',
    description: 'Tạo hồ sơ nhân viên và thông tin công việc.',
    personal: 'Thông tin cá nhân',
    contact: 'Thông tin liên hệ',
    employment: 'Thông tin công việc',
    employeeNumber: 'Mã nhân viên',
    firstName: 'Tên',
    middleName: 'Tên đệm',
    lastName: 'Họ',
    employeeNumberAuto: 'Tự động tạo sau khi lưu',
    preferredName: 'Tên gọi',
    email: 'Email',
    phone: 'Số điện thoại',
    gender: 'Giới tính',
    dateOfBirth: 'Ngày sinh',
    nationalId: 'CCCD / Mã định danh',
    maritalStatus: 'Tình trạng hôn nhân',
    address: 'Địa chỉ',
    workType: 'Hình thức làm việc',
    employmentType: 'Loại hợp đồng',
    contractEndDate: 'Ngày hết hạn hợp đồng',
    jobTitle: 'Chức danh',
    department: 'Phòng ban',
    location: 'Địa điểm làm việc',
    supervisorName: 'Quản lý trực tiếp',
    joinedDate: 'Ngày vào làm',
    optional: 'Không bắt buộc',
    select: 'Chọn',
    male: 'Nam',
    female: 'Nữ',
    other: 'Khác',
    single: 'Độc thân',
    married: 'Đã kết hôn',
    divorced: 'Ly hôn',
    widowed: 'Góa',
    fullTime: 'Toàn thời gian',
    partTime: 'Bán thời gian',
    contract: 'Hợp đồng',
    intern: 'Thực tập',
    permanent: 'Không thời hạn',
    fixedTerm: 'Có thời hạn',
    temporary: 'Tạm thời',
    cancel: 'Hủy',
    save: 'Lưu nhân viên',
    saving: 'Đang lưu...',
    required: 'Vui lòng nhập trường bắt buộc.',
    invalidEmail: 'Email không hợp lệ.',
    errorTitle: 'Không thể tạo nhân viên',
  },
  en: {
    title: 'Add employee',
    description: 'Create an employee profile and employment details.',
    personal: 'Personal information',
    contact: 'Contact information',
    employment: 'Employment details',
    employeeNumber: 'Employee number',
    firstName: 'First name',
    middleName: 'Middle name',
    lastName: 'Last name',
    employeeNumberAuto: 'Generated automatically after saving',
    preferredName: 'Preferred name',
    email: 'Email',
    phone: 'Phone',
    gender: 'Gender',
    dateOfBirth: 'Date of birth',
    nationalId: 'National ID',
    maritalStatus: 'Marital status',
    address: 'Address',
    workType: 'Work type',
    employmentType: 'Employment type',
    contractEndDate: 'Contract end date',
    jobTitle: 'Job title',
    department: 'Department',
    location: 'Work location',
    supervisorName: 'Supervisor',
    joinedDate: 'Joined date',
    optional: 'Optional',
    select: 'Select',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    single: 'Single',
    married: 'Married',
    divorced: 'Divorced',
    widowed: 'Widowed',
    fullTime: 'Full time',
    partTime: 'Part time',
    contract: 'Contract',
    intern: 'Intern',
    permanent: 'Permanent',
    fixedTerm: 'Fixed term',
    temporary: 'Temporary',
    cancel: 'Cancel',
    save: 'Save employee',
    saving: 'Saving...',
    required: 'This field is required.',
    invalidEmail: 'Enter a valid email address.',
    errorTitle: 'Unable to create employee',
  },
} as const;
