import type { Company, Department } from '@/components/organization/company/CompanyTypes';

export const initialCompanies: Company[] = [
  {
    id: 'hiu',
    code: 'HIU',
    name: 'Đại học Quốc tế Hồng Bàng',
    employees: 487,
    departments: 18,
    location: 'TP. Hồ Chí Minh',
    taxCode: '0303857068',
    active: true,
  },
  {
    id: 'hsa',
    code: 'HSA',
    name: 'Học viện Sức khỏe',
    employees: 216,
    departments: 9,
    location: 'TP. Hồ Chí Minh',
    taxCode: '0303857069',
    active: true,
  },
  {
    id: 'hitech',
    code: 'HTC',
    name: 'Công ty Công nghệ HIU',
    employees: 84,
    departments: 6,
    location: 'TP. Thủ Đức',
    taxCode: '0303857070',
    active: true,
  },
  {
    id: 'her',
    code: 'HER',
    name: 'Viện Nghiên cứu Giáo dục',
    employees: 43,
    departments: 4,
    location: 'TP. Hồ Chí Minh',
    taxCode: '0303857071',
    active: true,
  },
];

export const initialDepartments: Department[] = [
  {
    id: 'hiu-bgh',
    companyId: 'hiu',
    code: 'BGH',
    name: 'Ban Giám hiệu',
    owner: 'Nguyễn Minh Quân',
    employees: 5,
    active: true,
  },
  {
    id: 'hiu-pns',
    companyId: 'hiu',
    code: 'PNS',
    name: 'Phòng Nhân sự',
    owner: 'Trần Thu Hà',
    employees: 12,
    active: true,
  },
  {
    id: 'hiu-ptc',
    companyId: 'hiu',
    code: 'PTC',
    name: 'Phòng Tài chính – Kế toán',
    owner: 'Lê Hoàng Nam',
    employees: 9,
    active: true,
  },
  {
    id: 'hiu-cntt',
    companyId: 'hiu',
    code: 'CNTT',
    name: 'Trung tâm Công nghệ thông tin',
    owner: 'Võ Thành Công',
    employees: 21,
    active: true,
  },
  {
    id: 'hiu-daqt',
    companyId: 'hiu',
    code: 'DAQT',
    name: 'Ban Dự án quốc tế',
    owner: 'Chưa bổ nhiệm',
    employees: 0,
    active: false,
  },
];
