export const companyText = {
  code: ['Mã', 'Code'],
  department: ['Phòng ban', 'Department'],
  manager: ['Trưởng đơn vị', 'Manager'],
  people: ['Nhân sự', 'People'],
  status: ['Trạng thái', 'Status'],
  active: ['Hoạt động', 'Active'],
  inactive: ['Tạm ngưng', 'Inactive'],
  editDepartment: ['Chỉnh sửa phòng ban', 'Edit department'],
  pageTitle: ['Cơ cấu tập đoàn', 'Group structure'],
  pageDescription: [
    'Công ty thành viên và phòng ban trực thuộc',
    'Subsidiaries and their departments',
  ],
  addCompany: ['Thêm công ty', 'Add company'],
  parentGroup: ['Tập đoàn mẹ', 'Parent group'],
  companies: ['Công ty', 'Companies'],
  employees: ['Nhân sự', 'Employees'],
  companyList: ['Danh sách công ty', 'Company list'],
  subsidiaries: ['Công ty thành viên', 'Subsidiaries'],
  departmentsLower: ['phòng ban', 'departments'],
  peopleLower: ['nhân sự', 'people'],
  currentlyActive: ['Đang hoạt động', 'Active'],
  edit: ['Chỉnh sửa', 'Edit'],
  departments: ['Phòng ban', 'Departments'],
  locations: ['Địa điểm', 'Locations'],
  jobTitles: ['Chức danh', 'Job titles'],
  directDepartments: ['Phòng ban trực thuộc', 'Departments'],
  directDepartmentsDescription: [
    'Cơ cấu bên trong công ty đang chọn',
    'Structure within the selected company',
  ],
  searchDepartments: ['Tìm phòng ban...', 'Search departments...'],
  addDepartment: ['Thêm phòng ban', 'Add department'],
  noDepartments: ['Không tìm thấy phòng ban', 'No departments found'],
  changeSearch: ['Thử thay đổi từ khóa tìm kiếm.', 'Try changing the search keyword.'],
  noCompanies: [
    'Chưa có công ty. Hãy thêm công ty đầu tiên.',
    'No companies yet. Add the first company.',
  ],
  deleteCompanyDetail: [
    'Các phòng ban thuộc công ty này cũng sẽ bị xóa.',
    'Departments belonging to this company will also be deleted.',
  ],
  companyRequiredError: [
    'Vui lòng nhập mã, tên và địa điểm công ty.',
    'Enter the company code, name, and location.',
  ],
  updateCompanyDescription: [
    'Cập nhật thông tin và trạng thái đơn vị.',
    'Update company information and status.',
  ],
  createCompanyDescription: [
    'Tạo một đơn vị mới trong cơ cấu tập đoàn.',
    'Create a new company in the group structure.',
  ],
  editCompany: ['Chỉnh sửa công ty', 'Edit company'],
  companyCode: ['Mã công ty', 'Company code'],
  companyName: ['Tên công ty', 'Company name'],
  location: ['Địa điểm', 'Location'],
  taxCode: ['Mã số thuế', 'Tax code'],
  employeeCount: ['Số nhân sự', 'Employees'],
  departmentCount: ['Số phòng ban', 'Departments'],
  deleteCompany: ['Xóa công ty', 'Delete company'],
  cancel: ['Hủy', 'Cancel'],
  saveChanges: ['Lưu thay đổi', 'Save changes'],
  createCompany: ['Tạo công ty', 'Create company'],
  departmentRequiredError: [
    'Vui lòng nhập mã và tên phòng ban.',
    'Enter the department code and name.',
  ],
  notAssigned: ['Chưa bổ nhiệm', 'Not assigned'],
  updateDepartmentDescription: [
    'Điều chỉnh thông tin phòng ban đang chọn.',
    'Update the selected department.',
  ],
  createDepartmentDescription: [
    'Thêm phòng ban vào công ty đang chọn.',
    'Add a department to the selected company.',
  ],
  departmentCode: ['Mã phòng ban', 'Department code'],
  departmentName: ['Tên phòng ban', 'Department name'],
  deleteDepartment: ['Xóa phòng ban', 'Delete department'],
  createDepartment: ['Tạo phòng ban', 'Create department'],
  irreversible: ['Thao tác này không thể hoàn tác.', 'This action cannot be undone.'],
  confirmDelete: ['Xác nhận xóa', 'Confirm deletion'],
  deleteQuestion: ['Bạn có chắc muốn xóa', 'Are you sure you want to delete'],
  keep: ['Giữ lại', 'Keep'],
  delete: ['Xóa', 'Delete'],
  groupName: ['HIU Group', 'HIU Group'],
  companyCodeExample: ['VD: HSA', 'E.g. HSA'],
  departmentCodeExample: ['VD: PNS', 'E.g. HR'],
  locationExample: ['TP. Hồ Chí Minh', 'Ho Chi Minh City'],
} as const;

export type CompanyTextKey = keyof typeof companyText;

export function getCompanyText(locale: string, key: CompanyTextKey) {
  return companyText[key][locale === 'en' ? 1 : 0];
}
