import type { Employee } from '@/types/employee/employee';

export const employeeMockData: Employee[] = [
  {
    id: 'emp-1001',
    employeeNumber: 'E1001',
    firstName: 'Minh',
    middleName: 'Quang',
    lastName: 'Nguyen',
    preferredName: 'Minh',
    email: 'minh.nguyen@hiuhrm.vn',
    phone: '0901 100 100',
    gender: 'MALE',
    dateOfBirth: '1994-06-18',
    nationalId: '079194001001',
    workType: 'FULL_TIME',
    employmentType: 'PERMANENT',
    contractEndDate: '',
    maritalStatus: 'MARRIED',
    address: 'Thu Duc, Ho Chi Minh City',
    status: 'ACTIVE',
    jobTitle: 'HR Executive',
    department: 'Human Resources',
    location: 'Ho Chi Minh City',
    supervisorName: 'Tran Thi Mai',
    joinedDate: '2024-02-12',
  },
  {
    id: 'emp-1002',
    employeeNumber: 'E1002',
    firstName: 'Linh',
    middleName: '',
    lastName: 'Tran',
    preferredName: 'Linh',
    email: 'linh.tran@hiuhrm.vn',
    phone: '0902 200 200',
    gender: 'FEMALE',
    dateOfBirth: '1997-12-04',
    nationalId: '001197120004',
    workType: 'FULL_TIME',
    employmentType: 'FIXED_TERM',
    contractEndDate: '2026-05-31',
    maritalStatus: 'SINGLE',
    address: 'Cau Giay, Ha Noi',
    status: 'PROBATION',
    jobTitle: 'Recruitment Specialist',
    department: 'Talent Acquisition',
    location: 'Ha Noi',
    supervisorName: 'Le Van Huy',
    joinedDate: '2025-05-06',
  },
  {
    id: 'emp-1003',
    employeeNumber: 'E1003',
    firstName: 'Bao',
    middleName: 'Anh',
    lastName: 'Pham',
    preferredName: 'Bao',
    email: 'bao.pham@hiuhrm.vn',
    phone: '0903 300 300',
    gender: 'MALE',
    dateOfBirth: '1992-09-22',
    nationalId: '079192092200',
    workType: 'FULL_TIME',
    employmentType: 'PERMANENT',
    contractEndDate: '',
    maritalStatus: 'MARRIED',
    address: 'Hai Chau, Da Nang',
    status: 'ON_LEAVE',
    jobTitle: 'Payroll Officer',
    department: 'Compensation',
    location: 'Da Nang',
    supervisorName: 'Nguyen Thi Loan',
    joinedDate: '2023-09-18',
  },
  {
    id: 'emp-1004',
    employeeNumber: 'E1004',
    firstName: 'Thao',
    middleName: '',
    lastName: 'Vo',
    preferredName: 'Thao',
    email: 'thao.vo@hiuhrm.vn',
    phone: '0904 400 400',
    gender: 'FEMALE',
    dateOfBirth: '1995-03-14',
    nationalId: '079195031404',
    workType: 'FULL_TIME',
    employmentType: 'PERMANENT',
    contractEndDate: '',
    maritalStatus: 'SINGLE',
    address: 'District 1, Ho Chi Minh City',
    status: 'ACTIVE',
    jobTitle: 'HR Generalist',
    department: 'Human Resources',
    location: 'Ho Chi Minh City',
    supervisorName: 'Tran Thi Mai',
    joinedDate: '2022-11-03',
  },
  {
    id: 'emp-1005',
    employeeNumber: 'E1005',
    firstName: 'Khanh',
    middleName: 'Duy',
    lastName: 'Le',
    preferredName: 'Khanh',
    email: 'khanh.le@hiuhrm.vn',
    phone: '0905 500 500',
    gender: 'MALE',
    dateOfBirth: '1991-01-27',
    nationalId: '079191012700',
    workType: 'FULL_TIME',
    employmentType: 'FIXED_TERM',
    contractEndDate: '2025-12-31',
    maritalStatus: 'MARRIED',
    address: 'Ninh Kieu, Can Tho',
    status: 'TERMINATED',
    jobTitle: 'Operations Analyst',
    department: 'Operations',
    location: 'Can Tho',
    supervisorName: 'Pham Duc Long',
    joinedDate: '2021-07-21',
  },
  {
    id: 'emp-1006',
    employeeNumber: 'E1006',
    firstName: 'Yen',
    middleName: '',
    lastName: 'Do',
    preferredName: 'Yen',
    email: 'yen.do@hiuhrm.vn',
    phone: '0906 600 600',
    gender: 'FEMALE',
    dateOfBirth: '1993-08-09',
    nationalId: '079193080900',
    workType: 'PART_TIME',
    employmentType: 'TEMPORARY',
    contractEndDate: '2026-01-31',
    maritalStatus: 'SINGLE',
    address: 'Binh Thanh, Ho Chi Minh City',
    status: 'ACTIVE',
    jobTitle: 'People Partner',
    department: 'People Operations',
    location: 'Ho Chi Minh City',
    supervisorName: 'Tran Thi Mai',
    joinedDate: '2024-08-15',
  },
  {
    id: 'emp-1007',
    employeeNumber: 'E1007',
    firstName: 'Hieu',
    middleName: 'Thanh',
    lastName: 'Nguyen',
    preferredName: 'Hieu',
    email: 'hieu.nguyen@hiuhrm.vn',
    phone: '0907 700 700',
    gender: 'MALE',
    dateOfBirth: '2001-11-20',
    nationalId: '079201112000',
    workType: 'INTERN',
    employmentType: 'INTERN',
    contractEndDate: '2026-08-31',
    maritalStatus: 'SINGLE',
    address: 'Go Vap, Ho Chi Minh City',
    status: 'PROBATION',
    jobTitle: 'HR Intern',
    department: 'Human Resources',
    location: 'Ho Chi Minh City',
    supervisorName: 'Nguyen Thi Loan',
    joinedDate: '2025-06-10',
  },
  {
    id: 'emp-1008',
    employeeNumber: 'E1008',
    firstName: 'Phuc',
    middleName: '',
    lastName: 'Bui',
    preferredName: 'Phuc',
    email: 'phuc.bui@hiuhrm.vn',
    phone: '0908 800 800',
    gender: 'MALE',
    dateOfBirth: '1990-05-15',
    nationalId: '001190051500',
    workType: 'FULL_TIME',
    employmentType: 'PERMANENT',
    contractEndDate: '',
    maritalStatus: 'MARRIED',
    address: 'Hai Ba Trung, Ha Noi',
    status: 'ACTIVE',
    jobTitle: 'C&B Specialist',
    department: 'Compensation',
    location: 'Ha Noi',
    supervisorName: 'Le Van Huy',
    joinedDate: '2023-03-29',
  },
];
