export const mockLeaveRequests = [
  {
    id: '1',
    name: 'Nguyễn Văn A',
    type: 'Phép năm',
    duration: '2 ngày',
    date: '15/07 - 16/07',
    status: 'pending',
    avatar: 'NA',
  },
  {
    id: '2',
    name: 'Trần Thị B',
    type: 'Nghỉ ốm',
    duration: '1 ngày',
    date: '14/07',
    status: 'approved',
    avatar: 'TB',
  },
  {
    id: '3',
    name: 'Lê Văn C',
    type: 'Phép năm',
    duration: '0.5 ngày',
    date: '12/07',
    status: 'rejected',
    avatar: 'LC',
  },
  {
    id: '4',
    name: 'Phạm Thị D',
    type: 'Nghỉ thai sản',
    duration: '180 ngày',
    date: '01/08 - 28/01',
    status: 'approved',
    avatar: 'PD',
  },
  {
    id: '5',
    name: 'Hoàng Văn E',
    type: 'Không lương',
    duration: '3 ngày',
    date: '10/07 - 12/07',
    status: 'pending',
    avatar: 'HE',
  },
];
