export const LeaveListText = {
  vi: {
    title: 'Nghỉ phép',
    description: 'Quản lý yêu cầu, phê duyệt và số dư phép của nhân viên.',
    create: 'Tạo đơn phép',
    pending: 'Chờ duyệt',
    approvedWeek: 'Đã duyệt tuần này',
    rejected: 'Từ chối',
    onLeave: 'Đang nghỉ',
    tabRequests: 'Yêu cầu phê duyệt',
    tabHistory: 'Lịch sử',
    colEmployee: 'Nhân viên',
    colType: 'Loại nghỉ',
    colDuration: 'Thời gian',
    colStatus: 'Trạng thái',
    statusPending: 'Chờ duyệt',
    statusApproved: 'Đã duyệt',
    statusRejected: 'Từ chối',
  },
  en: {
    title: 'Leave',
    description: 'Manage employee leave requests, approvals, and balances.',
    create: 'Create request',
    pending: 'Pending',
    approvedWeek: 'Approved this week',
    rejected: 'Rejected',
    onLeave: 'On leave',
    tabRequests: 'Requests',
    tabHistory: 'History',
    colEmployee: 'Employee',
    colType: 'Type',
    colDuration: 'Duration',
    colStatus: 'Status',
    statusPending: 'Pending',
    statusApproved: 'Approved',
    statusRejected: 'Rejected',
  },
} as const;
