export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REFRESH_TOKEN: '/auth/refresh-token',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
  },
  USER: {
    ROOT: '/users',
    DETAIL: (id: string) => `/users/${id}`,
  },
  EMPLOYEE: {
    ROOT: '/employees',
    DETAIL: (id: string) => `/employees/${id}`,
    PERSONAL: (id: string) => `/employees/${id}/personal`,
    JOB: (id: string) => `/employees/${id}/job`,
    SALARY: (id: string) => `/employees/${id}/salary`,
    DOCUMENTS: (id: string) => `/employees/${id}/documents`,
  },
  ORGANIZATION: {
    ROOT: '/organizations',
    LOCATIONS: '/organizations/locations',
    DEPARTMENTS: '/organizations/departments',
    JOB_TITLES: '/organizations/job-titles',
  },
  LEAVE: {
    ROOT: '/leaves',
    DETAIL: (id: string) => `/leaves/${id}`,
    TYPES: '/leave-types',
    ENTITLEMENTS: '/leave-entitlements',
    BALANCES: '/leave-balances',
    APPROVE: (id: string) => `/leaves/${id}/approve`,
    REJECT: (id: string) => `/leaves/${id}/reject`,
    CANCEL: (id: string) => `/leaves/${id}/cancel`,
  },
  ATTENDANCE: {
    ROOT: '/attendance',
    PUNCH_IN: '/attendance/punch-in',
    PUNCH_OUT: '/attendance/punch-out',
    DETAIL: (id: string) => `/attendance/${id}`,
    DAILY: '/attendance/daily',
    LOGS: '/attendance/logs',
    RECALCULATE: (id: string) => `/attendance/${id}/recalculate`,
    EXCEPTIONS: '/attendance/exceptions',
    ADJUSTMENTS: '/attendance/adjustments',
  },
  WORKFORCE: {
    SHIFTS: '/workforce/shifts',
    SHIFT_DETAIL: (id: string) => `/workforce/shifts/${id}`,
    SCHEDULES: '/workforce/schedules',
    SCHEDULE_DETAIL: (id: string) => `/workforce/schedules/${id}`,
    PUBLISH_SCHEDULE: '/workforce/schedules/publish',
    DUTY: '/workforce/duty',
    DUTY_DETAIL: (id: string) => `/workforce/duty/${id}`,
    OVERTIME: '/workforce/overtime',
    OVERTIME_DETAIL: (id: string) => `/workforce/overtime/${id}`,
    SHIFT_SWAPS: '/workforce/shift-swaps',
    SHIFT_SWAP_DETAIL: (id: string) => `/workforce/shift-swaps/${id}`,
    POLICIES: '/workforce/attendance-policies',
    POLICY_DETAIL: (id: string) => `/workforce/attendance-policies/${id}`,
    DEVICES: '/workforce/attendance-devices',
    DEVICE_DETAIL: (id: string) => `/workforce/attendance-devices/${id}`,
    ALLOWANCES: '/workforce/allowance-rules',
    ALLOWANCE_DETAIL: (id: string) => `/workforce/allowance-rules/${id}`,
    CLOSING: '/workforce/attendance-closing',
  },
  TIMESHEET: {
    ROOT: '/timesheets',
    DETAIL: (id: string) => `/timesheets/${id}`,
    SUBMIT: (id: string) => `/timesheets/${id}/submit`,
    APPROVE: (id: string) => `/timesheets/${id}/approve`,
    REJECT: (id: string) => `/timesheets/${id}/reject`,
  },
  RECRUITMENT: {
    VACANCIES: '/recruitment/vacancies',
    VACANCY_DETAIL: (id: string) => `/recruitment/vacancies/${id}`,
    CANDIDATES: '/recruitment/candidates',
    CANDIDATE_DETAIL: (id: string) => `/recruitment/candidates/${id}`,
    APPLICATIONS: '/recruitment/applications',
    INTERVIEWS: '/recruitment/interviews',
  },
  PERFORMANCE: {
    KPI: '/performance/kpis',
    GOALS: '/performance/goals',
    REVIEWS: '/performance/reviews',
    APPRAISALS: '/performance/appraisals',
  },
  REPORT: {
    ROOT: '/reports',
  },
} as const;
