export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REFRESH_TOKEN: '/auth/refresh-token',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
  },
  USER: {
    ROOT: '/users',
    DETAIL: (id: string) => `/users/${id}`,
  },
  EMPLOYEE: {
    ROOT: '/employees',
    DETAIL: (id: string) => `/employees/${id}`,
    PERSONAL: (id: string) => `/employees/${id}/personal`,
    JOB: (id: string) => `/employees/${id}/job`,
    SALARY: (id: string) => `/employees/${id}/salary`,
    DOCUMENTS: (id: string) => `/employees/${id}/documents`,
  },
  ORGANIZATION: {
    ROOT: '/organizations',
    LOCATIONS: '/organizations/locations',
    DEPARTMENTS: '/organizations/departments',
    JOB_TITLES: '/organizations/job-titles',
  },
  LEAVE: {
    ROOT: '/leaves',
    DETAIL: (id: string) => `/leaves/${id}`,
    TYPES: '/leave-types',
    ENTITLEMENTS: '/leave-entitlements',
    BALANCES: '/leave-balances',
    APPROVE: (id: string) => `/leaves/${id}/approve`,
    REJECT: (id: string) => `/leaves/${id}/reject`,
    CANCEL: (id: string) => `/leaves/${id}/cancel`,
  },
  ATTENDANCE: {
    ROOT: '/attendance',
    PUNCH_IN: '/attendance/punch-in',
    PUNCH_OUT: '/attendance/punch-out',
  },
  TIMESHEET: {
    ROOT: '/timesheets',
    DETAIL: (id: string) => `/timesheets/${id}`,
    SUBMIT: (id: string) => `/timesheets/${id}/submit`,
    APPROVE: (id: string) => `/timesheets/${id}/approve`,
    REJECT: (id: string) => `/timesheets/${id}/reject`,
  },
  RECRUITMENT: {
    VACANCIES: '/recruitment/vacancies',
    VACANCY_DETAIL: (id: string) => `/recruitment/vacancies/${id}`,
    CANDIDATES: '/recruitment/candidates',
    CANDIDATE_DETAIL: (id: string) => `/recruitment/candidates/${id}`,
    APPLICATIONS: '/recruitment/applications',
    INTERVIEWS: '/recruitment/interviews',
  },
  PERFORMANCE: {
    KPI: '/performance/kpis',
    GOALS: '/performance/goals',
    REVIEWS: '/performance/reviews',
    APPRAISALS: '/performance/appraisals',
  },
  REPORT: {
    ROOT: '/reports',
  },
} as const;
