export const AttendanceListText = {
  vi: {
    title: 'Dữ liệu Chấm công',
    description: 'Theo dõi giờ vào/ra, đi trễ, về sớm và xuất bảng công.',
    export: 'Xuất dữ liệu',
    onTime: 'Đúng giờ',
    late: 'Đi trễ',
    absent: 'Vắng mặt',
    overtime: 'Tăng ca',
    tabDaily: 'Chấm công hôm nay',
    tabHistory: 'Lịch sử theo tháng',
    colEmployee: 'Nhân viên',
    colDepartment: 'Phòng ban',
    colCheckIn: 'Giờ vào',
    colCheckOut: 'Giờ ra',
    colStatus: 'Trạng thái',
  },
  en: {
    title: 'Attendance Data',
    description: 'Track check-ins, check-outs, lateness, and export timesheets.',
    export: 'Export Data',
    onTime: 'On Time',
    late: 'Late',
    absent: 'Absent',
    overtime: 'Overtime',
    tabDaily: 'Daily Attendance',
    tabHistory: 'Monthly History',
    colEmployee: 'Employee',
    colDepartment: 'Department',
    colCheckIn: 'Check In',
    colCheckOut: 'Check Out',
    colStatus: 'Status',
  },
} as const;
