export const mockAttendanceRecords = [
  {
    id: '1',
    name: 'Nguyễn Văn A',
    department: 'Kỹ thuật',
    checkIn: '08:00',
    checkOut: '17:30',
    status: 'on-time',
    avatar: 'NA',
  },
  {
    id: '2',
    name: 'Trần Thị B',
    department: 'Nhân sự',
    checkIn: '08:15',
    checkOut: '17:00',
    status: 'late',
    avatar: 'TB',
  },
  {
    id: '3',
    name: 'Lê Văn C',
    department: 'Thiết kế',
    checkIn: '--:--',
    checkOut: '--:--',
    status: 'absent',
    avatar: 'LC',
  },
  {
    id: '4',
    name: 'Phạm Thị D',
    department: 'Kinh doanh',
    checkIn: '07:55',
    checkOut: '18:15',
    status: 'overtime',
    avatar: 'PD',
  },
  {
    id: '5',
    name: 'Hoàng Văn E',
    department: 'Kỹ thuật',
    checkIn: '08:05',
    checkOut: '17:05',
    status: 'late',
    avatar: 'HE',
  },
];
